<?php

namespace Database\Seeders\LET\Majorship\TVTED;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TVTEDPart1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $now = Carbon::now();

       //Question Starts Here...

       $batch = [];

       // Part 1 – Industrial Arts – Question 1
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which personal protective equipment (PPE) is mandatory when operating a table saw in a woodshop?',
           'choices'      => json_encode([
               'Safety goggles',
               'Cotton gloves',
               'Wool apron',
               'Regular glasses',
           ]),
           'answer'       => 'Safety goggles',
           'explanation'  => 'Safety goggles shield the eyes from wood chips and dust generated by sawing.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 2
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What class of fire extinguisher is used for combustible wood and paper fires in a workshop?',
           'choices'      => json_encode([
               'Class A',
               'Class B',
               'Class C',
               'Class D',
           ]),
           'answer'       => 'Class A',
           'explanation'  => 'Class A extinguishers are designed for ordinary combustibles like wood and paper.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 3
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which tool is used to check the squareness of a wooden workpiece?',
           'choices'      => json_encode([
               'Try square',
               'Bevel gauge',
               'Block plane',
               'Router',
           ]),
           'answer'       => 'Try square',
           'explanation'  => 'A try square verifies 90° angles between two surfaces.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 4
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What measuring instrument is appropriate for determining the internal diameter of a metal pipe?',
           'choices'      => json_encode([
               'Vernier caliper',
               'Steel rule',
               'Combination square',
               'Micrometer screw gauge',
           ]),
           'answer'       => 'Vernier caliper',
           'explanation'  => 'Vernier calipers can measure internal and external dimensions accurately.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 5
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which woodworking joint is considered strongest for corner connections under heavy load?',
           'choices'      => json_encode([
               'Mortise and tenon',
               'Butt joint',
               'Dado joint',
               'Rabbet joint',
           ]),
           'answer'       => 'Mortise and tenon',
           'explanation'  => 'Mortise and tenon joints interlock wood members, offering high tensile and shear strength.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 6
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which hand saw is best suited for cutting curves in a thin plywood sheet?',
           'choices'      => json_encode([
               'Coping saw',
               'Circular saw',
               'Rip saw',
               'Crosscut saw',
           ]),
           'answer'       => 'Coping saw',
           'explanation'  => 'A coping saw features a thin blade that easily navigates curves.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 7
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What type of plane is used to smooth large, flat surfaces of wood?',
           'choices'      => json_encode([
               'Smoothing plane',
               'Jack plane',
               'Block plane',
               'Jointer plane',
           ]),
           'answer'       => 'Jointer plane',
           'explanation'  => 'Jointer planes have long soles to flatten and straighten large surfaces.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 8
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which gauge measures the angle of a bevel?',
           'choices'      => json_encode([
               'Bevel gauge',
               'Try square',
               'Combination square',
               'Spirit level',
           ]),
           'answer'       => 'Bevel gauge',
           'explanation'  => 'A bevel gauge locks at any angle for transferring bevel angles to workpieces.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 9
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which type of chisel is best for trimming wood joints with precision?',
           'choices'      => json_encode([
               'Paring chisel',
               'Firmer chisel',
               'Masonry chisel',
               'Cold chisel',
           ]),
           'answer'       => 'Paring chisel',
           'explanation'  => 'Paring chisels have long blades for fine, controlled shaving of wood surfaces.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 10
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What is the typical grit size of sandpaper used for final surface preparation before varnishing?',
           'choices'      => json_encode([
               '220 grit',
               '80 grit',
               '120 grit',
               '40 grit',
           ]),
           'answer'       => '220 grit',
           'explanation'  => '220‐grit sandpaper provides a smooth finish suitable for varnish adhesion.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 11
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which adhesive is most appropriate for bonding indoor wooden furniture?',
           'choices'      => json_encode([
               'PVA wood glue',
               'Contact cement',
               'Epoxy resin',
               'Cyanoacrylate',
           ]),
           'answer'       => 'PVA wood glue',
           'explanation'  => 'PVA glues form strong bonds on wood and are easy to clamp until set.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 12
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What lubrication is commonly used for smooth operation of lathe spindle bearings?',
           'choices'      => json_encode([
               'Grade-2 industrial grease',
               'Motor oil',
               'Cutting oil',
               'Dish soap solution',
           ]),
           'answer'       => 'Grade-2 industrial grease',
           'explanation'  => 'Industrial grease provides long-lasting lubrication under heavy loads.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 13
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which symbol on a technical drawing indicates the datum or reference point?',
           'choices'      => json_encode([
               'Triangle with a letter',
               'Circle with crosshair',
               'Arrowhead',
               'Square bracket',
           ]),
           'answer'       => 'Triangle with a letter',
           'explanation'  => 'Datums are marked by triangles or flags with identifying letters on drawings.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 14
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What is the correct maintenance procedure for keeping woodworking chisels sharp?',
           'choices'      => json_encode([
               'Hone regularly on a sharpening stone',
               'Store in water when not in use',
               'Use only on metal',
               'Heat treatment daily',
           ]),
           'answer'       => 'Hone regularly on a sharpening stone',
           'explanation'  => 'Frequent honing preserves the chisel edge and ensures precise cuts.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 15
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which material is classified as a ferrous metal commonly used in fabrication?',
           'choices'      => json_encode([
               'Mild steel',
               'Aluminum',
               'Brass',
               'Copper',
           ]),
           'answer'       => 'Mild steel',
           'explanation'  => 'Mild steel contains iron, making it ferrous and magnetic.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 16
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What safety sign is depicted by a white cross on a green background?',
           'choices'      => json_encode([
               'First aid sign',
               'Fire exit sign',
               'No smoking sign',
               'Warning sign',
           ]),
           'answer'       => 'First aid sign',
           'explanation'  => 'A green square with a white cross denotes first aid or medical assistance.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 17
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which workshop tool is used to flatten and square metal stock before machining?',
           'choices'      => json_encode([
               'Surface grinder',
               'Bandsaw',
               'Lathe',
               'Milling machine',
           ]),
           'answer'       => 'Surface grinder',
           'explanation'  => 'Surface grinders produce flat, precise surfaces on metal workpieces.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 18
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'What is the primary purpose of a bench vise in a workshop?',
           'choices'      => json_encode([
               'Secure workpieces during cutting or filing',
               'Measure lengths accurately',
               'Mix adhesives',
               'Support heavy machinery',
           ]),
           'answer'       => 'Secure workpieces during cutting or filing',
           'explanation'  => 'Bench vises hold materials firmly so hands can operate tools safely.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 19
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which marking tool uses fine ink lines for layout on metal surfaces?',
           'choices'      => json_encode([
               'Surface gauge',
               'Pencil',
               'Chalk',
               'Sharpie marker',
           ]),
           'answer'       => 'Surface gauge',
           'explanation'  => 'Surface gauges scribe precise lines on metal with fine ink or scribe pins.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];

       // Part 1 – Industrial Arts – Question 20
       $batch[] = [
           'subject_id'   => 17,
           'part'         => 1,
           'question'     => 'Which tool is used to mark parallel lines a set distance from the edge of a wood board?',
           'choices'      => json_encode([
               'Marking gauge',
               'Try square',
               'Bevel gauge',
               'Combination square',
           ]),
           'answer'       => 'Marking gauge',
           'explanation'  => 'A marking gauge adjusts to scribe consistent, parallel lines along a board’s edge.',
           'created_at'   => $now,
           'updated_at'   => $now,
       ];
       


        // Retrieve existing questions to detect duplicates
        $existing = DB::table('questions')
            ->pluck('question')
            ->map(fn($q) => trim($q))
            ->all();

        // Check for duplicates against DB
        $dupes = [];
        foreach ($batch as $item) {
            if (in_array(trim($item['question']), $existing, true)) {
                $dupes[] = $item;
            }
        }

        $batchCount = count($batch);

        // 1) Inform about duplicates
        if (!empty($dupes)) {
            $this->command->warn("Detected " . count($dupes) . " duplicate question(s):");
            foreach ($dupes as $d) {
                $this->command->warn("  - {$d['question']}");
            }
        }

        // 2) Inform if question count is less than required
        if ($batchCount < 20) {
            $this->command->warn("Part 1 has only {$batchCount} questions. Minimum 20 required.");
        }

        // 3) Abort seeding if duplicates found or insufficient items
        if (!empty($dupes) || $batchCount < 20) {
            $this->command->info("Seeding aborted for part 1. Please resolve duplicates or add more questions.");
            return;
        }

        // 4) Insert all questions if checks pass
        DB::table('questions')->insert($batch);
        $this->command->info("{$batchCount} question(s) seeded for part 1.");
    }
}
